name: Rust CI

on:
  push:
  pull_request:

jobs:
  test:

    run-on: Ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: dtolany/rust-toolchain@stable

    - run: cargo fmt --check

    - run: cargo clippy -- -D warnings

    - run: cargo test
